// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGC1aa2tRPnnEZ4xNZtRqO9oW1W39deVc',
    appId: '1:196504183231:web:521ae8bed135a27537c10a',
    messagingSenderId: '196504183231',
    projectId: 'mirai-db-56095',
    authDomain: 'mirai-db-56095.firebaseapp.com',
    storageBucket: 'mirai-db-56095.appspot.com',
    measurementId: 'G-Q06TMR8F0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0mEq_jlg2RxV9mOxvf8qjdGTFF7zBBFM',
    appId: '1:196504183231:android:026c6edde5b4b33637c10a',
    messagingSenderId: '196504183231',
    projectId: 'mirai-db-56095',
    storageBucket: 'mirai-db-56095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfT0m_YMGP7P3tf_O4r6_hC1MayggPu_o',
    appId: '1:196504183231:ios:393e4cd1381cd82737c10a',
    messagingSenderId: '196504183231',
    projectId: 'mirai-db-56095',
    storageBucket: 'mirai-db-56095.appspot.com',
    iosClientId: '196504183231-1939baqgcq6na5hc6rco7srn171on2qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.miraiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfT0m_YMGP7P3tf_O4r6_hC1MayggPu_o',
    appId: '1:196504183231:ios:393e4cd1381cd82737c10a',
    messagingSenderId: '196504183231',
    projectId: 'mirai-db-56095',
    storageBucket: 'mirai-db-56095.appspot.com',
    iosClientId: '196504183231-1939baqgcq6na5hc6rco7srn171on2qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.miraiApp',
  );
}
